# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: pt

pipeline:
# No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# If you'd like to customize it, uncomment and adjust the pipeline.
# See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: "SpacyNLP"
    model: "pt_core_news_lg"
    case_sensitive: False
  - name: "SpacyTokenizer"
    "intent_tokenization_flag": True
  - name: "SpacyFeaturizer"
    "pooling": "mean"
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: SpacyEntityExtractor
  - name: EntitySynonymMapper
  - name: DIETClassifier
    epochs: 100
    model_confidence: linear_norm
    constrain_similarities: true
    ranking_length: 5
    use_masked_language_model: True
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: faq
    model_confidence: linear_norm
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.80
    # ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# No configuration for policies was provided. The following default policies were used to train your model.
# If you'd like to customize them, uncomment and adjust the policies.
# See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  # - name: TEDPolicy
    # max_history: 5
    # epochs: 100
    # model_confidence: linear_norm
    # constrain_similarities: true
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True



